# PHP CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-php/ for more details
version: 2
jobs:
  build-vite:
    docker:
      - image: node:16-alpine
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache if `package-lock.json` does not change
          name: Restore node modules cache
          keys:
              - node-v1-{{ checksum "package-lock.json" }}
              # fallback to using the latest cache if no exact match is found (See https://circleci.com/docs/2.0/caching/)
              - node-v1-
      - run:
          name: Install npm dependencies
          command: |
            cd ./buildchain
            npm install
      - save_cache: # special step to save the dependency cache with the `package-lock.json` cache key template
          name: Save node modules cache
          key: node-v1-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Run bundler build task
          command: |
            npm run build
workflows:
  version: 2
  build:
    jobs:
      - build-vite
